### PR TITLE
Introduce SHARE_INSTALL_DIR to install arch-independent data

### PR DESCRIPTION
**Pull request by heirecka**
This is helpful on a multiarch layout where the prefix is
/usr/${host} but arch-independent files should still be installed
into /usr/share.

### CODE REVIEW

**Comment by user-none** [comment]
SHARE_INSTALL_DIR should be set in the Linux specific section because it does not apply to any other platform.

**Comment by heirecka** [comment]
Sorry. As a packager of a Linux distro I sometimes seem to forget that there are other platforms. I updated the pull request.

**Comment by user-none** [comment]
I'm still only seeing one commit. Did you forget to push it?

**Comment by heirecka** [comment]
I amended the commit and force pushed. I never had to update a pull request on github before, next time time I'll add an extra commit.

**Comment by user-none** [comment]
There were some issues I saw with the pull request. I pushed up a variation that should resolve your issue.

**Pull request closed without merging**
